server:
  host: localhost
  port: 3000
  cors:
    - "http://0.0.0.0:4200"
    - "http://127.0.0.1:4200"
    - "http://localhost:4200"
swaggerUsers:
  title: Priv'Attic public API
  description: The Users API description
  version: 1.0
  tag: users
  path: documentation
swaggerPosts:
  title: Priv'Attic public API
  description: The Posts API description
  version: 1.0
  tag: posts
  path: documentation
swaggerAuth:
  title: Priv'Attic public API
  description: The Authentification API description
  version: 1.0
  tag: auth
  path: documentation
swaggerComments:
  title: Priv'Attic public API
  description: The Comments API description
  version: 1.0
  tag: comments
  path: documentation

swaggerLikes:
  title: Priv'Attic public API
  description: The Likes API description
  version: 1.0
  tag: likes
  path: documentation
mongodb:
  uri: mongodb://localhost:27017/nwt
